{% set version = "0.3.5" %}

package:
  name: gridded
  version: {{ version }}

source:
  url: https://github.com/NOAA-ORR-ERD/gridded/archive/v{{ version }}.tar.gz
  sha256: 64f4c9ab71445c98d7da975ff59f17cba5860d5add3f2e251855e76261881e5a

build:
    noarch: python
    number: 2
    script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python =2.7|>=3.7
    - pip
  run:
    - python =2.7|>=3.7
    - six
    - numpy
    - scipy
    - netcdf4
    - cell_tree2d

test:
  requires:
    - pytest

  imports:
    - gridded

  commands:
    - pytest --pyargs gridded

about:
  home: https://github.com/NOAA-ORR-ERD/gridded
  license: BSD-3-Clause
  license_file: LICENSE
  summary: |
    A library designed to represent grid-aligned data and provide a variety of
    processing functions, netCDF file reading/writing, and CF, UGrid, and SGrid
    standard compatibility.

  description: |
    Gridded is a unification of the pysgrid, pyugrid, and a data representation
    layer that is designed to provide an intuitive and flexible system for
    reading and representing gridded data from a variety of sources. It is also
    a library to contain useful functions for processing gridded data.

extra:
  recipe-maintainers:
    - jay-hennen
    - ChrisBarker-NOAA
