travis:
  secure:
    BINSTAR_TOKEN: l6mL2ghNyCRYBC8HLGNncduSE+RiEuhX1yD2OHdMAWlVsE1YUNyYIuKhBmsjq3rmloimLVEdCafjTZG9hQbbNRb82vfodriAgysaUMMD4dzH2JvZMbBR64O6u5HBb+Idy2nV8IozaN84awDVyLmRUQhp48u04/Hxt6rYVNtfAnBIU1AzXactnBgHDX16y2TRahPI5r4JkmtokRBaEb6ynaA8E0LvMtjfV8gQRTd7Sy9N6cuUzdhYEuDcjouaHGl7q3GKe6elDCGmH9ExoYQc0hWbWdhHp4k/M7Pn9Kt5qAQ8OC4MBQ9uLqnVdnCplWDdFhIWB96tKKyKoK+6HCMJywc3yH7/TPPhSNkFrtihqxaQPhjELvEHFwsRHFigb5U1yl30xJK4GOWV7vlv6EwIVqil9/LhyML8Q/wC9NrZGCJyqjl3Tq1YTKLTqIjNrUL6qH/s3qMYUvxTR/yGoBgo9+0Oqj0NxF3l6iHrhfEnbVaZ1zv11k+tgdp/TLt4r2qGjFFMp5Um5cBOp19RfCnwKCO+1PjyS/aR93csDOhEVUjeZx4wz4ch9gUGTy2hmLJNZzaLcBCNdmm7n8iQwx1qbvjEcEAHTvWhar51BaHXCS0/HUPwbMN/aE6X355e5fS7fdCB0owG+DPt7BOjCbAYcCquu6M5vFRcwOX+SmPhTDQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
